CREATE TABLE IF NOT EXISTS candidates (
    candidate_id TEXT PRIMARY KEY,
    family TEXT NOT NULL,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    parameters_json TEXT NOT NULL,
    risk_json TEXT NOT NULL DEFAULT '{}',
    net_profit REAL NOT NULL DEFAULT 0,
    max_drawdown REAL NOT NULL DEFAULT 0,
    profit_factor REAL NOT NULL DEFAULT 0,
    sharpe REAL NOT NULL DEFAULT 0,
    trade_count INTEGER NOT NULL DEFAULT 0,
    win_rate REAL NOT NULL DEFAULT 0,
    mll_breached INTEGER NOT NULL DEFAULT 0,
    mll_buffer REAL NOT NULL DEFAULT 0,
    correlation_cluster TEXT,
    validation_status TEXT NOT NULL,
    rejection_reason TEXT,
    robustness_score REAL NOT NULL DEFAULT 0,
    topstep_passed INTEGER NOT NULL DEFAULT 0,
    topstep_score REAL NOT NULL DEFAULT 0,
    combine_days_to_pass INTEGER,
    combine_profit_target_hit INTEGER NOT NULL DEFAULT 0,
    combine_mll_breached INTEGER NOT NULL DEFAULT 0,
    combine_min_mll_buffer REAL NOT NULL DEFAULT 0,
    combine_best_day_profit REAL NOT NULL DEFAULT 0,
    combine_best_day_pct_of_total_profit REAL NOT NULL DEFAULT 0,
    combine_consistency_ok INTEGER NOT NULL DEFAULT 0,
    target_inflation_required INTEGER NOT NULL DEFAULT 0,
    funded_sim_survived INTEGER NOT NULL DEFAULT 0,
    payout_eligible INTEGER NOT NULL DEFAULT 0,
    payout_days_to_eligibility INTEGER,
    payout_cycles_survived INTEGER NOT NULL DEFAULT 0,
    gross_payout_available REAL NOT NULL DEFAULT 0,
    trader_net_payout REAL NOT NULL DEFAULT 0,
    post_payout_mll_breach INTEGER NOT NULL DEFAULT 0,
    internal_daily_stop_used REAL NOT NULL DEFAULT 0,
    daily_profit_lock_used REAL NOT NULL DEFAULT 0,
    worst_day_loss REAL NOT NULL DEFAULT 0,
    max_consecutive_losing_days INTEGER NOT NULL DEFAULT 0,
    winning_days_150_count INTEGER NOT NULL DEFAULT 0,
    topstep_split_scores_json TEXT NOT NULL DEFAULT '{}',
    parent_candidate_id TEXT,
    mutation_type TEXT,
    created_at TEXT NOT NULL
);
